"""Add Team table

Revision ID: b2dc57a23723
Revises: f47cc2f459b1
Create Date: 2024-09-23 14:48:15.598008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2dc57a23723'
down_revision = 'f47cc2f459b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('Dept')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Dept', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
