"""New column

Revision ID: e34fb03040ca
Revises: 6b17e5cde7ce
Create Date: 2024-11-04 13:12:01.645603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e34fb03040ca'
down_revision = '6b17e5cde7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('Email')
        batch_op.drop_index('Staff_FName')

    op.drop_table('users')
    with op.batch_alter_table('work_arrangements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Manager_Reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_arrangements', schema=None) as batch_op:
        batch_op.drop_column('Manager_Reason')

    op.create_table('users',
    sa.Column('Staff_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Staff_FName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('Role', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Staff_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('Staff_FName', ['Staff_FName'], unique=True)
        batch_op.create_index('Email', ['Email'], unique=True)

    op.create_table('teams',
    sa.Column('Team_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Team_Name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Team_Lead_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Team_Size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Team_Lead_ID'], ['employees.Staff_ID'], name='teams_ibfk_1'),
    sa.PrimaryKeyConstraint('Team_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
