"""Add Team table

Revision ID: f47cc2f459b1
Revises: 8cd231779c26
Create Date: 2024-09-23 14:33:22.937819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f47cc2f459b1'
down_revision = '8cd231779c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('Team_Size',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('Team_Size',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
